# -*- coding: utf-8 -*-
"""Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KehcQOusck9efNRvNyB-PZFGv3waEC0K
"""

import pandas as pd
import random
import re

# Đường dẫn file Excel
file_path = '/Everyday language.xlsx'

def normalize(text):
    if isinstance(text, str):
        return re.sub(r'\s+', ' ', text.strip().lower())
    return ''

def load_data(sheet_choice):
    sheets_to_read = [f"Sheet{i}" for i in range(1, sheet_choice + 1)]
    df_list = []
    for sheet in sheets_to_read:
        try:
            df = pd.read_excel(file_path, sheet_name=sheet)
            df.columns = ['Vocabulary', 'Phonetic', 'Meaning', 'Example']
            df = df.dropna()
            df_list.append(df)
        except Exception as e:
            print(f"Cannot read {sheet}: {e}")
    combined_df = pd.concat(df_list, ignore_index=True)
    for col in ['Vocabulary', 'Phonetic', 'Meaning', 'Example']:
        combined_df[col + '_norm'] = combined_df[col].apply(normalize)
    return combined_df

def get_random_entries(df, exclude_indexes, count):
    attempts = 0
    selected = []
    used_texts = set()

    while len(selected) < count and attempts < 10000:
        idx = random.randint(0, len(df) - 1)
        if idx in exclude_indexes or idx in selected:
            attempts += 1
            continue

        row = df.iloc[idx]
        key_texts = [row['Vocabulary_norm'], row['Phonetic_norm'], row['Example_norm']]

        if any(text in used_texts for text in key_texts):
            attempts += 1
            continue

        selected.append(idx)
        used_texts.update(key_texts)
        attempts = 0  # reset sau khi chọn thành công

    if len(selected) < count:
        print(f"\n❌ Không thể chọn đủ {count} câu hỏi hợp lệ. Dữ liệu hiện tại có thể không đủ.\n")
        return None
    return selected

def run_quiz(df, indexes, mode='vocab_to_meaning'):
    print("\n👉 Trả lời 25 câu hỏi. Không phản hồi đúng/sai cho đến khi kết thúc.\n")
    results = []

    for i, idx in enumerate(indexes, 1):
        row = df.iloc[idx]
        if mode == 'vocab_to_meaning':
            prompt_type = random.choice(['Vocabulary', 'Phonetic', 'Example'])
            prompt = row[prompt_type]
            correct_answer = row['Meaning_norm']
            show_answer = row['Meaning']
            question = f"{i}. {prompt_type}: {prompt}\n   → Nghĩa là gì? "
        else:
            prompt = row['Meaning']
            correct_answer = row['Vocabulary_norm']
            show_answer = row['Vocabulary']
            question = f"{i}. Nghĩa: {prompt}\n   → Từ vựng là gì? "

        user_input = normalize(input(question))
        is_correct = user_input == correct_answer
        results.append((i, is_correct, show_answer))

    correct_count = sum(1 for _, ok, _ in results if ok)
    print(f"\n🎯 Bạn đã trả lời đúng {correct_count}/25 câu.")
    if correct_count >= 20:
        print("🎉 Bạn đã vượt qua bài kiểm tra!\n")
    else:
        print("🔁 Bạn chưa vượt qua bài kiểm tra.\n")

    if correct_count < 25:
        print("📌 Những câu bạn đã trả lời sai:")
        for i, ok, correct in results:
            if not ok:
                print(f"  - Câu {i}: Đáp án đúng là: {correct}")

    return set(indexes)

def main():
    print("📝 CHƯƠNG TRÌNH HỌC TỪ VỰNG\n")
    while True:
        try:
            sheet_num = int(input("Chọn số sheet muốn học (1–10): "))
            if 1 <= sheet_num <= 10:
                break
            else:
                print("❗ Nhập số từ 1 đến 10.")
        except:
            print("❗ Vui lòng nhập số.")

    df = load_data(sheet_num)
    print(f"✅ Đã tải {len(df)} từ vựng từ {sheet_num} sheet.")

    round_num = 1
    while True:
        print(f"\n🔄 VÒNG KIỂM TRA {round_num}")

        print("\n--- KIỂM TRA 1: Cho từ/phiên âm/ví dụ → tìm nghĩa ---")
        used_indexes = get_random_entries(df, set(), 25)
        if used_indexes is None:
            break
        used_set = run_quiz(df, used_indexes, mode='vocab_to_meaning')

        print("\n--- KIỂM TRA 2: Cho nghĩa → tìm từ vựng ---")
        remaining_indexes = get_random_entries(df, used_set, 25)
        if remaining_indexes is None:
            break
        run_quiz(df, remaining_indexes, mode='meaning_to_vocab')

        again = input("\n👉 Bạn có muốn làm tiếp vòng kiểm tra khác? (y/n): ").strip().lower()
        if again != 'y':
            print("\n👋 Kết thúc chương trình. Hẹn gặp lại!")
            break

        round_num += 1

if __name__ == "__main__":
    main()